version: "3.8"
services:
  discovery:
    build: ../Eureka Server
    ports:
      - "8761:8761"
    image: "discovery-service"

  candidat1:
    build: .  # Le chemin actuel, car le Docker Compose est déjà dans le dossier "microservice"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "3000:8082"
    image: "candidate-service"

  candidat2:
    build: .  # Le chemin actuel
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "3001:8083"
    image: "candidate-service"
